# Generated by Django 4.2.10 on 2024-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=10)),
                ('traveller_name', models.CharField(max_length=100)),
                ('traveller_number', models.CharField(max_length=15)),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('traveller_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
