# Generated by Django 4.2.10 on 2024-02-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('vehicle_id', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=100)),
                ('trip_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='route.route')),
            ],
        ),
    ]
